name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - '**/*'  # Any file in any directory

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU (optional, for multi-platform builds)
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: yochaigal/kettlewright:latest
        cache-from: type=registry,ref=yochaigal/kettlewright:latest
        cache-to: type=registry,mode=max,ref=yochaigal/kettlewright:latest
